languageCode = "zh-cn"
languageName = "ç®€ä½“ä¸­æ–‡"
weight = 9
title = "å¶å­ğŸƒ"

[params]
  displayName = "ç®€ä½“ä¸­æ–‡"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/author.webp"
  description = "ç”Ÿå‘½ä¸­çš„æ¯ä¸ªç‚¹æ»´ï¼Œæˆ‘éƒ½æƒ³è¦çæƒœ"

[params.author]
  name = "x"
  image = "img/author.webp"
  headline = "ä¸€åç»…å£«çš„åšå®¢"
  bio = "ç”Ÿæ´»ä¸æ­¢çœ¼å‰çš„è‹Ÿä¸”ï¼Œè¿˜æœ‰è¯—å’Œè¿œæ–¹çš„ç”°é‡ã€‚"
  links = [
    { x-twitter = "https://twitter.com/spirit" },
    { github = "https://github.com/xxspa" },
  ]